// https://securite-sociale-alimentation.org/les-dynamiques-locales/carte-des-initiatives-locales-de-la-ssa/
var initiatives_ssa = [
    {
        "name": "Collectif Acclimat’action",
        "type": "initiative SSA",
        "Structures porteuses": ["Vrac Bordeaux","les râteleurs","supercoop","capsciences","CeDS","Du vert dans les rouages","e-graine","L'estey","Moisa et MIAM - acteurs issus de l’éducation populaire de l’économie sociale et solidaire du travail social ou de la recherche scientifique"],
        "Territoire d’expérimentation": "Bordeaux métropole et pays foyen",
        "Partenaires": ["l’ADEME", "la Région Nouvelle Aquitaine", "la Fondation Carasso", "la Fondation Européenne pour le Climat", "Bordeaux Métropole", "le Conseil Départemental de Gironde et la Ville de Bordeaux"],
        "lat": 44.8775859,
        "lng": -0.5717582,
        "address": "Av. André Reinson",
        "postcode": "33300",
        "city": "Bordeaux",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour réfléchir et expérimenter dans les quartiers populaires",
        "URLs": ["https://www.acclimataction.fr/", "https://securite-sociale-alimentation.org/initiative/collectif-acclimataction-pour-reflechir-et-experimenter-dans-les-quartiers-populaires/"]
    },
    {
        "name": "Caisse commune de l’alimentation Montpellier",
        "type": "initiative SSA",
        "Structures porteuses": ["Réseau cocagne", "Secours Catholique France", "VRAC", "UGESS", "Réseau Civam"],
        "Territoire d’expérimentation": "Montpellier, France",
        "Partenaires": ["collectif national « Accès digne à l’alimentation »"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "",
        "city": "Montpellier",
        "website": "https://tav-montpellier.xyz/?Experimentation",
        "phone": "",
        "email": "",
        "summary": "Un collectif informel de 25 organisations mobilisé pour monter une expérimentation autour de la démocratie alimentaire.",
        "URLs": ["https://tav-montpellier.xyz/?Experimentation"]
    },
    {
        "name": "Collectif SSA 35",
        "type": "initiative SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Ille-et-Vilaine (35)",
        "Partenaires": ["Alternatiba", "AMAP", "ATTAC Rennes", "CIVAM", "Le P’tit Blosneur", "Maison de la consommation et l’environnement"],
        "lat": 48.1173,
        "lng": -1.6778,
        "address": "Place de la Gare",
        "postcode": "35000",
        "city": "Rennes",
        "website": "",
        "phone": "",
        "email": "collectif-ssa35@protonmail.com",
        "summary": "Le Collectif SSA 35 mène différentes actions pour faire connaître la proposition politique au grand public et mobiliser pour la création de la SSA.",
        "URLs": []
    },
    {
        "name": "Bureaux SSA 33",
        "type": "initiative SSA",
        "Structures porteuses": ["ATD Quart Monde Gironde", "Collectif pour une transition citoyenne Gironde", "Réseau Salariat Gironde"],
        "Territoire d’expérimentation": "Bordeaux Métropole",
        "Partenaires": ["Les Amis de la Terre Gironde", "VRAC Bordeaux", "Les Landes Solidaires"],
        "lat": 44.8378,
        "lng": -0.5792,
        "address": "Bordeaux",
        "postcode": "",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/bordeaux/",
        "phone": "",
        "email": "ssa.bordeaux@gmail.com",
        "summary": "Un lieu pour échanger et construire ensemble autour des questions alimentaires.",
        "URLs": ["https://securite-sociale-alimentation.org/bordeaux/"]
    },
    {
        "name": "Collectif SSA 69",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Lyon", "La Légumerie", "Les Petits Débrouillards Rhône-Alpes"],
        "Territoire d’expérimentation": "Lyon et ses environs",
        "Partenaires": ["La Gonette", "Cocagne Haute Dombes", "La Caravane des possibles"],
        "lat": 45.764043,
        "lng": 4.835659,
        "address": "Lyon",
        "postcode": "69000",
        "city": "Lyon",
        "website": "",
        "phone": "",
        "email": "collectifssa69@gmail.com",
        "summary": "Pour une sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": []
    },
    {
        "name": "SSA Toulouse",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Amis de la Terre Midi-Pyrénées", "ATTAC Toulouse", "Réseau Salariat Toulouse"],
        "Territoire d’expérimentation": "Toulouse",
        "Partenaires": ["VRAC Toulouse", "Terre de liens Midi-Pyrénées", "ADEPES"],
        "lat": 43.6047,
        "lng": 1.4442,
        "address": "Toulouse",
        "postcode": "31000",
        "city": "Toulouse",
        "website": "",
        "phone": "",
        "email": "ssa.toulouse@gmail.com",
        "summary": "Expérimenter une sécurité sociale de l’alimentation dans la ville rose.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Grenoble",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Habiles", "VRAC Grenoble", "Alliance PEC Isère"],
        "Territoire d’expérimentation": "Grenoble et son agglomération",
        "Partenaires": ["ATD Quart Monde", "ATTAC Isère", "Les Petits Débrouillards Isère"],
        "lat": 45.1885,
        "lng": 5.7245,
        "address": "Grenoble",
        "postcode": "38000",
        "city": "Grenoble",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Une dynamique locale pour la sécurité sociale de l’alimentation.",
        "URLs": []
    },
    {
        "name": "Collectif SSA 31",
        "type": "initiative SSA",
        "Structures porteuses": ["Réseau Salariat Haute-Garonne", "AMAP 31", "Terre de Liens"],
        "Territoire d’expérimentation": "Haute-Garonne",
        "Partenaires": ["ATTAC Toulouse", "Les Amis de la Terre Midi-Pyrénées"],
        "lat": 43.6043,
        "lng": 1.4437,
        "address": "Toulouse",
        "postcode": "",
        "city": "Toulouse",
        "website": "",
        "phone": "",
        "email": "ssa31@gmail.com",
        "summary": "Pour une alimentation digne et durable en Haute-Garonne.",
        "URLs": []
    },
    {
        "name": "Collectif SSA 75",
        "type": "initiative SSA",
        "Structures porteuses": ["AMAP Ile-de-France", "Réseau Salariat Paris", "Terre de Liens IDF"],
        "Territoire d’expérimentation": "Paris et petite couronne",
        "Partenaires": ["ATTAC Paris", "Les Amis de la Terre IDF"],
        "lat": 48.8566,
        "lng": 2.3522,
        "address": "Paris",
        "postcode": "75000",
        "city": "Paris",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation en Île-de-France.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nantes",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nantes", "Alliance PEC", "Réseau Salariat"],
        "Territoire d’expérimentation": "Nantes et sa métropole",
        "Partenaires": ["Les Amis de la Terre Loire-Atlantique", "ATTAC Nantes"],
        "lat": 47.2184,
        "lng": -1.5536,
        "address": "Nantes",
        "postcode": "44000",
        "city": "Nantes",
        "website": "",
        "phone": "",
        "email": "ssa.nantes@gmail.com",
        "summary": "Un collectif pour la sécurité sociale de l’alimentation à Nantes.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Lyon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Lyon", "Les Petits Débrouillards Rhône-Alpes", "La Légumerie"],
        "Territoire d’expérimentation": "Lyon et alentours",
        "Partenaires": ["Cocagne Haute Dombes", "La Gonette", "La Caravane des possibles"],
        "lat": 45.764043,
        "lng": 4.835659,
        "address": "Lyon",
        "postcode": "69000",
        "city": "Lyon",
        "website": "",
        "phone": "",
        "email": "ssa.lyon@gmail.com",
        "summary": "Promotion de la sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Marseille",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Marseille", "Les Petits Débrouillards PACA", "Les Amis de la Terre PACA"],
        "Territoire d’expérimentation": "Marseille et environs",
        "Partenaires": ["ATTAC Marseille", "Réseau Salariat PACA"],
        "lat": 43.2965,
        "lng": 5.3698,
        "address": "Marseille",
        "postcode": "13000",
        "city": "Marseille",
        "website": "",
        "phone": "",
        "email": "ssa.marseille@gmail.com",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Marseille.",
        "URLs": []
    }
];
